---
- debug:
    var: _ceph_elemental_net_cephosd

- name: extract custom resource data
  set_fact:
    ceph_osd_cr_namespace: '{{ meta.namespace }}'
    ceph_osd_cr_name: '{{ meta.name }}'
    ceph_osd_cr_api_version: '{{ _ceph_elemental_net_cephosd.apiVersion }}'
    ceph_osd_cr_kind: '{{ _ceph_elemental_net_cephosd.kind }}'
    ceph_osd_cr_uid: '{{ _ceph_elemental_net_cephosd.metadata.uid }}'
    ceph_osd_cr_api_group: "{{ _ceph_elemental_net_cephosd.apiVersion.split('/')[0] }}"
    ceph_osd_storage: "{{ _ceph_elemental_net_cephosd.spec.storage }}"
    ceph_osd_pod_template: "{{ _ceph_elemental_net_cephosd.spec.podTemplate }}"
    ceph_osd_pod_template_hash: "{{ lookup('dicthash', _ceph_elemental_net_cephosd.spec.podTemplate)[:16] }}"

- block:
  - name: lookup running pods
    set_fact:
      k8s_gvks: "{{ q('k8s', api_version='v1', kind='Pod', namespace=ceph_osd_cr_namespace,
                      label_selector=ceph_osd_cr_api_group + '/owner=' + ceph_osd_cr_kind + '-' + ceph_osd_cr_name) }}"
  rescue:
  - name: no running pods found
    set_fact:
      k8s_gvks: []

- name: build list of pods from running pods
  set_fact:
    ceph_osd_pods: "{{ lookup('template', 'k8s-pod-list.json.j2') | from_json }}"

- name: build list of pods from configuration
  set_fact:
    ceph_osd_pods_configured: "{{ lookup('template', 'configured-pod-list.json.j2') | from_json }}"

- name: calculate missing pods
  set_fact:
    ceph_osd_pods_missing: "{{ ceph_osd_pods_configured.keys() | difference(ceph_osd_pods.uptodate.keys() | union(ceph_osd_pods.outofdate.keys())) | list }}"

- name: calculate superfluous pods
  set_fact:
    ceph_osd_pods_superfluous: "{{ ceph_osd_pods.uptodate.keys() | union(ceph_osd_pods.outofdate.keys()) | difference(ceph_osd_pods_configured.keys()) | list }}"

- debug:
    var: ceph_osd_pods_missing

- debug:
    var: ceph_osd_pods_superfluous

- debug:
    var: ceph_osd_pods.invalid

- debug:
    var: ceph_osd_pods.outofdate

- debug:
    var: ceph_osd_pods.terminating

- name: delete invalid pods
  k8s:
    state: absent
    api_version: v1
    kind: Pod
    namespace: "{{ ceph_osd_cr_namespace }}"
    name: "{{ item }}"
  loop: "{{ ceph_osd_pods.invalid }}"

- name: delete superfluous pods
  k8s:
    state: absent
    api_version: v1
    kind: Pod
    namespace: "{{ ceph_osd_cr_namespace }}"
    name: "{{ item }}"
  when: item in ceph_osd_pods_superfluous
  loop: "{{ ceph_osd_pods.uptodate.keys() }}"

- name: create pods
  k8s:
    state: present
    definition: "{{ ceph_osd_pod_template | combine(lookup('template', 'pod-overrides.yaml.j2') | from_yaml, recursive=True) }}"
    force: True
  vars:
    ceph_osd_pod_name: "{{ '{}-{}'.format(item.key, lookup('password', '/dev/null length=4 chars=ascii_lowercase,digits')) }}"
    ceph_osd_host: "{{ item.value.host }}"
    ceph_osd_data: "{{ item.value.osd.data }}"
    ceph_osd_db: "{{ item.value.osd.db | default(None) }}"
    ceph_osd_wal: "{{ item.value.osd.wal | default(None) }}"
  when: item.key in ceph_osd_pods_missing
  loop: "{{ lookup('dict', ceph_osd_pods_configured) }}"
