---
- debug:
    var: _ceph_elemental_net_cephosd

- name: extract custom resource data
  set_fact:
    ceph_osd_cr_namespace: '{{ meta.namespace }}'
    ceph_osd_cr_name: '{{ meta.name }}'
    ceph_osd_cr_api_version: '{{ _ceph_elemental_net_cephosd.apiVersion }}'
    ceph_osd_cr_kind: '{{ _ceph_elemental_net_cephosd.kind }}'
    ceph_osd_cr_uid: '{{ _ceph_elemental_net_cephosd.metadata.uid }}'
    ceph_osd_cr_api_group: "{{ _ceph_elemental_net_cephosd.apiVersion.split('/')[0] }}"
    ceph_osd_storage: "{{ _ceph_elemental_net_cephosd.spec.storage }}"
    ceph_osd_pod_template: "{{ _ceph_elemental_net_cephosd.spec.podTemplate }}"
    ceph_osd_pod_template_hash: "{{ lookup('dicthash', _ceph_elemental_net_cephosd.spec.podTemplate)[:16] }}"
    ceph_osd_update_domain: "{{ _ceph_elemental_net_cephosd.spec.updateDomain }}"

- block:
    - name: lookup running pods
      set_fact:
        k8s_gvks: "{{ query('k8s', api_version='v1', kind='Pod', namespace=ceph_osd_cr_namespace,
                            label_selector=ceph_osd_cr_api_group + '/owner=' + ceph_osd_cr_kind + '-' + ceph_osd_cr_name) }}"
  rescue:
    - name: no running pods found
      set_fact:
        k8s_gvks: []

- name: build list of pods from configuration
  set_fact:
    ceph_osd_pods_configured: "{{ lookup('template', 'configured-pod-list.json.j2') | from_json }}"

- name: build list of pods from running pods
  set_fact:
    ceph_osd_pods: "{{ lookup('template', 'k8s-pod-list.json.j2') | from_json }}"

- name: build union of all configured and already existing pods
  set_fact:
    ceph_osd_pods_existing: >
      {{ ceph_osd_pods.uptodate | combine(ceph_osd_pods.outofdate, ceph_osd_pods.ready, ceph_osd_pods.unready) }}

- name: calculate missing pods
  set_fact:
    ceph_osd_pods_missing: "{{ ceph_osd_pods_configured.keys() | difference(ceph_osd_pods_existing.keys()) | list }}"

- name: calculate superfluous pods
  set_fact:
    ceph_osd_pods_superfluous: "{{ ceph_osd_pods_existing.keys() | difference(ceph_osd_pods_configured.keys()) | list }}"

- debug:
    msg: "Missing: {{ ceph_osd_pods_missing | sort | join(', ') }}"

- debug:
    msg: "Superfluous: {{ ceph_osd_pods_superfluous | sort | join(', ') }}"

- debug:
    msg: "Invalid: {{ ceph_osd_pods.invalid | sort | join(', ') }}"

- debug:
    msg: "Up-to-date: {{ ceph_osd_pods.uptodate.keys() | sort | join(', ') }}"

- debug:
    msg: "Out-of-date: {{ ceph_osd_pods.outofdate.keys() | sort | join(', ') }}"

- debug:
    msg: "Ready: {{ ceph_osd_pods.ready.keys() | sort | join(', ') }}"

- debug:
    msg: "Unready: {{ ceph_osd_pods.unready.keys() | sort | join(', ') }}"

- name: delete invalid pods
  k8s:
    state: absent
    api_version: v1
    kind: Pod
    namespace: "{{ ceph_osd_cr_namespace }}"
    name: "{{ item }}"
  loop: "{{ ceph_osd_pods.invalid }}"

- name: delete superfluous pods
  k8s:
    state: absent
    api_version: v1
    kind: Pod
    namespace: "{{ ceph_osd_cr_namespace }}"
    name: "{{ item.value.pod.metadata.name }}"
  when: item.key in ceph_osd_pods_superfluous
  loop: "{{ query('dict', ceph_osd_pods_existing) }}"

- name: create missing pods
  k8s:
    state: present
    definition: "{{ lookup('template', 'render-pod-definition.json.j2') | from_json }}"
    force: true
  vars:
    ceph_osd_pod_name: "{{ item.value.pod_name_prefix + lookup('password', '/dev/null length=5 chars=ascii_lowercase,digits') }}"
    ceph_osd_host: "{{ item.value.host }}"
    ceph_osd_data: "{{ item.value.osd.data }}"
    ceph_osd_db: "{{ item.value.osd.db | default(None) }}"
    ceph_osd_wal: "{{ item.value.osd.wal | default(None) }}"
  when: item.key in ceph_osd_pods_missing
  loop: "{{ query('dict', ceph_osd_pods_configured) }}"

- name: set pod-state of out-of-date pods to out-of-date
  k8s:
    state: present
    api_version: v1
    kind: Pod
    namespace: "{{ ceph_osd_cr_namespace }}"
    name: "{{ item.value.pod.metadata.name }}"
    definition: "{{ {'metadata': {'annotations': {ceph_osd_cr_api_group + '/pod-state': 'out-of-date'}}} }}"
  when: >
    (ceph_osd_cr_api_group + '/pod-state') not in item.value.pod.metadata.annotations or
      item.value.pod.metadata.annotations[ceph_osd_cr_api_group + '/pod-state'] != 'out-of-date'
  loop: "{{ query('dict', ceph_osd_pods.outofdate) }}"

- name: set pod-state of ready pods to up-to-date
  k8s:
    state: present
    api_version: v1
    kind: Pod
    namespace: "{{ ceph_osd_cr_namespace }}"
    name: "{{ item.value.pod.metadata.name }}"
    definition: "{{ {'metadata': {'annotations': {ceph_osd_cr_api_group + '/pod-state': 'up-to-date'}}} }}"
  when: >
    (ceph_osd_cr_api_group + '/pod-state') not in item.value.pod.metadata.annotations or
      item.value.pod.metadata.annotations[ceph_osd_cr_api_group + '/pod-state'] != 'up-to-date'
  loop: "{{ query('dict', ceph_osd_pods.ready) }}"

- name: set pod-state of up-to-date pods to up-to-date
  k8s:
    state: present
    api_version: v1
    kind: Pod
    namespace: "{{ ceph_osd_cr_namespace }}"
    name: "{{ item.value.pod.metadata.name }}"
    definition: "{{ {'metadata': {'annotations': {ceph_osd_cr_api_group + '/pod-state': 'up-to-date'}}} }}"
  when: >
    (ceph_osd_cr_api_group + '/pod-state') not in item.value.pod.metadata.annotations or
      item.value.pod.metadata.annotations[ceph_osd_cr_api_group + '/pod-state'] != 'up-to-date'
  loop: "{{ query('dict', ceph_osd_pods.uptodate) }}"


# Initializing ceph_osd_update_candidates is necessary as when is evaluated for each loop item, see below.
- set_fact:
    ceph_osd_update_candidates: "{{ [] }}"

- name: update out-of-date pod(s) by recreating it/them
  block:
    - block:
        - set_fact:
            # Sorting ensures that we'll advance host by host
            ceph_osd_update_osd: "{{ (ceph_osd_pods.outofdate.keys() | sort)[0] }}"
        - set_fact:
            ceph_osd_update_candidates: "{{ [ceph_osd_pods.outofdate[ceph_osd_update_osd]] }}"
      when: ceph_osd_update_domain == "OSD"

    - block:
        - set_fact:
            ceph_osd_update_host: "{{ (ceph_osd_pods.outofdate.values() | map(attribute='host') | unique | sort)[0] }}"
        - set_fact:
            # Requires Jinja2 >= 2.8
            ceph_osd_update_candidates: "{{ ceph_osd_pods.outofdate.values() | selectattr('host', 'equalto', ceph_osd_update_host) | list }}"
      when: ceph_osd_update_domain == "Host"

    - name: delete out-of-date pod(s)
      k8s:
        state: absent
        api_version: v1
        kind: Pod
        namespace: "{{ ceph_osd_cr_namespace }}"
        name: "{{ item.pod.metadata.name }}"
      loop: "{{ ceph_osd_update_candidates }}"

    - name: create new up-to-date pod(s)
      k8s:
        state: present
        definition: "{{ lookup('template', 'render-pod-definition.json.j2') | from_json | combine({'metadata': {'annotations': {ceph_osd_cr_api_group + '/pod-state': 'wait-for-ready'}}}, recursive=True) }}"
        force: true
      vars:
        ceph_osd_pod_name: "{{ item.pod_name_prefix + lookup('password', '/dev/null length=5 chars=ascii_lowercase,digits') }}"
        ceph_osd_host: "{{ item.host }}"
        ceph_osd_data: "{{ item.osd.data }}"
        ceph_osd_db: "{{ item.osd.db | default(None) }}"
        ceph_osd_wal: "{{ item.osd.wal | default(None) }}"
      loop: "{{ ceph_osd_update_candidates }}"
  when: ceph_osd_pods.outofdate | length > 0 and ceph_osd_pods.unready | length == 0
