# permissions for end users to view cephosds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cephosd-viewer-role
rules:
- apiGroups:
  - ceph.elemental.net
  resources:
  - cephosds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ceph.elemental.net
  resources:
  - cephosds/status
  verbs:
  - get
