apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-osd-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ceph-osd-operator
  template:
    metadata:
      labels:
        name: ceph-osd-operator
    spec:
      serviceAccountName: ceph-osd-operator
      containers:
        - name: ceph-osd-operator
          image: elementalnet/ceph-osd-operator:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 60000
            name: metrics
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "ceph-osd-operator"
