apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ceph-osd-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - "*"
- apiGroups:
  - ceph.elemental.net
  resources:
  - '*'
  verbs:
  - watch
  - get
  - list
  - update
