---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Build operator image
      command:
        cmd: docker build -t '{{ operator_image }}:latest' .
        chdir: '{{ project_dir }}'
      environment:
        DOCKER_BUILDKIT: '1'
      changed_when: false

    - name: Load image into registry
      command: docker push '{{ operator_image }}:latest'
      register: result
      changed_when: '"Pushed" in result.stdout'

- import_playbook: ../default/converge.yml
