---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - import_tasks: install.yml

    - name: Create test kind cluster
      command: "{{ kind }} create cluster --name osdk-test --kubeconfig {{ kubeconfig }} --config cluster-config.yml"
