apiVersion: ceph.elemental.net/v1alpha1
kind: CephOSD
metadata:
  name: ceph-osds
spec:
  storage:
    - hosts:
        - osdk-test-worker
        - osdk-test-worker2
      osds:
        - data: '/dev/disk/by-slot/pci-0000:5c:00.0-encl-0:7:0-slot-1'
          db: '/dev/disk/by-slot/pci-0000:5c:00.0-encl-0:7:0-slot-10-part1'
          wal: '/dev/disk/by-slot/pci-0000:5c:00.0-encl-0:7:0-slot-10-part2'
        - data: '/dev/disk/by-slot/pci-0000:5c:00.0-encl-0:7:0-slot-2'
          db: '/dev/disk/by-slot/pci-0000:5c:00.0-encl-0:7:0-slot-10-part3'
          wal: '/dev/disk/by-slot/pci-0000:5c:00.0-encl-0:7:0-slot-10-part4'
  updateDomain: "Host"
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        role: osd
    spec:
      containers:
        - image: busybox
          command:
            - /bin/sh
            - -c
            - >
              sleep 11;
              [ "$TEST" == "test123" ] && [ -n "$OSD_DEVICE" ] && [ -n "$OSD_DB_DEVICE" ] && [ -n "$OSD_WAL_DEVICE" ] && touch /tmp/healthy;
              sleep 365d
          env:
            - name: "TEST"
              value: "test123"
          imagePullPolicy: IfNotPresent
          name: busybox
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/healthy
            initialDelaySeconds: 2
            periodSeconds: 5
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
      priorityClassName: ceph-osd
      tolerations:
        - key: node.kubernetes.io/unschedulable
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/not-ready
          operator: Exists
        - key: node.kubernetes.io/unreachable
          operator: Exists
