# Adds namespace to all resources.
namespace: osdk-test

namePrefix: osdk-

patchesStrategicMerge:
- manager_image.yaml
- debug_logs_patch.yaml
- ../default/manager_auth_proxy_patch.yaml

resources:
- ../crd
- ../rbac
- ../manager
images:
- name: testing
  newName: testing-operator
patches:
- path: pull_policy/Never.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
