# Adds namespace to all resources.
namespace: osdk-test

namePrefix: osdk-

patchesStrategicMerge:
# - debug_logs_patch.yaml
- ../default/manager_auth_proxy_patch.yaml

resources:
- ../crd
- ../rbac
- ../manager
images:
- name: controller
  newName: localhost:5000/testing-operator
patches:
- path: pull_policy/Always.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
