---
- name: Converge
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
    custom_resource: "{{ lookup('file', '/'.join([deploy_dir, 'example/ceph_v1alpha1_cephosd_cr.yaml'])) | from_yaml }}"
  tasks:
  - name: Create the ceph.elemental.net/v1alpha1.CephOSD resource
    k8s:
      state: present
      namespace: '{{ namespace }}'
      definition: '{{ custom_resource }}'

- name: Converge
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  roles:
    - cephosd

- import_playbook: '{{ playbook_dir }}/asserts.yml'
