#!/bin/bash
if [ $# -gt 1 ]; then
  echo "usage: $(basename $0) [<job-id>]" 1>&2
  exit 1
fi

declare -r job="${1:-latest}"

kubectl exec -c ansible $(kubectl get pod -l name=ceph-osd-operator -o 'jsonpath={.items[0].metadata.name}') -- \
  sh -c 'cat /tmp/ansible-operator/runner/ceph.elemental.net/v1alpha1/CephOSD/default/*/artifacts/'"$job"'/stdout' | less
