#!/bin/bash
if [ $# != 2 ]; then
  echo "usage: $(basename $0) <custom-resource> <job-id>" 1>&2
  exit 1
fi

kubectl exec $(kubectl get pod -l name=ceph-osd-operator -o 'jsonpath={.items[0].metadata.name}') -- \
  cat /tmp/ansible-operator/runner/ceph.elemental.net/v1alpha1/CephOSD/default/$1/artifacts/$2/stdout | less
